import { createContext, useContext, useState, useEffect } from "react";

const translations = {
  en: {
    // Navigation
    home: "Home",
    about: "About",
    healthcare: "Healthcare",
    education: "Education",
    markets: "Markets",
    transport: "Transport",
    contact: "Contact",
    contactUs: "Contact Us",
    services: "Services",

    // Hero
    welcomeToKotulpur: "Welcome to the Heart of Kotulpur",
    discover: "Discover",
    theBeautyOfKotulpur: "The Beauty of Kotulpur",
    tagline:
      "A place where traditions come alive, communities thrive, and every corner tells a story.",
    discoverKotulpur: "Discover Kotulpur",
    ourServices: "Our Services",

    // Popular Section
    featuredGallery: "Featured Gallery",
    popularInKotulpur: "Popular in Kotulpur",
    discoverLoved:
      "Discover the most loved places and moments captured by our community",
    dragToExplore: "Drag to explore",
    autoPlaying: "Auto-playing gallery",

    // Services
    ourServicesTitle: "Our Services",
    comprehensiveServices:
      "Comprehensive services that make Kotulpur a wonderful place to live.",
    healthcare: "Healthcare",
    healthcareDesc: "Quality medical care for all residents.",
    education: "Education",
    educationDesc: "Schools and learning centers for all ages.",
    markets: "Markets",
    marketsDesc: "Fresh produce and daily necessities.",
    transport: "Transport",
    transportDesc: "Connected to major city hubs.",
    essentialInfrastructure: "Essential Infrastructure",
    coreServices: "Core Services",
    coreServicesDesc: "Core services that keep our community running smoothly.",
    learnMore: "Learn More",

    // Community
    communityCares: "A Community That Cares",
    communityCaresDesc:
      "Kotulpur is more than just a locality—it's a family. Our community comes together during festivals, supports each other in times of need, and works collectively to maintain our shared spaces.",
    communityCaresDesc2:
      "From morning yoga sessions in the park to evening cultural programs, life in Kotulpur is vibrant and fulfilling.",
    growingCommunity: "Be Part of Our Growing Community",
    growingCommunityDesc:
      "Whether you're a long-time resident or new to Kotulpur, there's always a place for you here.",

    // About Page
    ourStory: "Our Story",
    aboutKotulpur: "About Kotulpur",
    aboutDesc:
      "Kotulpur is a vibrant locality with a rich history and a promising future. Nestled in the heart of the region, our community is known for its warm hospitality, cultural heritage, and spirit of togetherness.",
    exploreServices: "Explore Services",
    ourHeritage: "Our Heritage",
    legacyOfProgress: "A Legacy of Progress",
    legacyDesc:
      "Founded generations ago, Kotulpur has grown from a small village into a thriving community that balances tradition with modern progress.",
    legacyDesc2:
      "Our ancestors laid the foundation of what we enjoy today—a place where neighbors know each other by name, where festivals are celebrated with full enthusiasm, and where every new member is welcomed with open arms.",
    whatWeStandFor: "What We Stand For",
    ourValues: "Our Values",
    valuesDesc: "The principles that guide our community forward.",
    unity: "Unity",
    unityDesc: "Together we stand strong",
    educationValue: "Education",
    educationValueDesc: "Learning for life",
    culture: "Culture",
    cultureDesc: "Preserving our heritage",
    growth: "Growth",
    growthDesc: "Progress in harmony",
    residents: "Residents",
    businesses: "Businesses",
    yearsOfHistory: "Years of History",
    wantToLearnMore: "Want to Learn More?",
    wantToLearnMoreDesc:
      "Explore our services and discover everything Kotulpur has to offer.",

    // Services Page
    servicesWeProvide: "Services We Provide",
    servicesDesc:
      "From essential utilities to community programs, we ensure a high quality of life for all residents of Kotulpur.",
    waterSupply: "Water Supply",
    waterSupplyDesc: "24/7 clean water distribution across all areas.",
    electricity: "Electricity",
    electricityDesc: "Reliable power grid with minimal outages.",
    communityPrograms: "Community Programs",
    togetherWeGrow: "Together We Grow",
    greenInitiative: "Green Kotulpur Initiative",
    greenInitiativeDesc:
      "Tree planting, waste management, and environmental awareness programs.",
    seniorCitizenCare: "Senior Citizen Care",
    seniorCitizenCareDesc:
      "Health check-ups, social gatherings, and welfare schemes for elders.",
    youthDevelopment: "Youth Development",
    youthDevelopmentDesc:
      "Sports tournaments, skill workshops, and career guidance programs.",
    culturalPreservation: "Cultural Preservation",
    culturalPreservationDesc:
      "Music, dance, art exhibitions, and festivals celebrating our heritage.",
    getInvolved: "Get Involved",
    needAssistance: "Need Assistance?",
    needAssistanceDesc:
      "Our support team is here to help you with any queries or concerns.",
    contactSupport: "Contact Support",

    // Healthcare Page
    healthcareServices: "Healthcare Services",
    healthcareHero: "Quality Healthcare for Every Resident",
    healthcareHeroDesc:
      "Comprehensive medical facilities and wellness programs to keep our community healthy.",
    medicalFacilities: "Medical Facilities",
    medicalFacilitiesDesc:
      "State-of-the-art healthcare infrastructure serving Kotulpur and surrounding areas.",
    communityHealthCenter: "Kotulpur Community Health Center",
    communityHealthCenterDesc:
      "24/7 emergency services and general consultations.",
    lifecareDiagnostics: "LifeCare Diagnostics",
    lifecareDiagnosticsDesc: "Advanced pathology and imaging services.",
    dentalCarePlus: "Dental Care Plus",
    dentalCarePlusDesc: "Complete dental care with modern equipment.",
    primaryCare: "Primary Care",
    diagnosticLab: "Diagnostic Lab",
    dentalClinic: "Dental Clinic",
    servicesWeOffer: "Services We Offer",
    emergencyCare: "Emergency Care",
    emergencyCareDesc: "24/7 ambulance",
    generalMedicine: "General Medicine",
    generalMedicineDesc: "Experienced physicians",
    diagnostics: "Diagnostics",
    diagnosticsDesc: "Lab tests, X-ray, MRI",
    pharmacy: "Pharmacy",
    pharmacyDesc: "Round the clock",
    inpatientCare: "Inpatient Care",
    inpatientCareDesc: "24/7 nursing",
    dentalServices: "Dental Services",
    dentalServicesDesc: "All treatments",
    eyeCare: "Eye Care",
    eyeCareDesc: "Ophthalmology",
    wellness: "Wellness",
    wellnessDesc: "Yoga, meditation",
    patientsYearly: "Patients Yearly",
    qualifiedDoctors: "Qualified Doctors",
    emergency: "Emergency",
    satisfaction: "Satisfaction",
    details: "Details",
    beds: "50+",
    tests: "200+",
    doctors: "5",

    // Education Page
    educationServices: "Education Services",
    educationHero: "Empowering Through Knowledge",
    educationHeroDesc:
      "From preschool to higher education, Kotulpur nurtures bright minds for a better tomorrow.",
    educationalInstitutions: "Educational Institutions",
    institutionsDesc:
      "Quality education at every level, shaped by dedicated educators and modern pedagogy.",
    kotulpurCentralSchool: "Kotulpur Central School",
    kotulpurCentralSchoolDesc:
      "CBSE affiliated school with modern infrastructure and experienced faculty.",
    govindaramCollege: "Govindaram College",
    govindaramCollegeDesc:
      "Arts, Science, and Commerce streams with excellent placement record.",
    tinyTotsPreSchool: "Tiny Tots Pre-School",
    tinyTotsPreSchoolDesc:
      "Early childhood education focusing on holistic development.",
    k12: "K-12",
    higherEducation: "Higher Education",
    prePrimary: "Pre-Primary",
    students: "Students",
    teachers: "Teachers",
    passRate: "Pass Rate",
    awards: "Awards",
    beyondTextbooks: "Beyond Textbooks",
    holisticDevelopment: "Holistic Development",
    holisticDesc:
      "Our institutions go beyond academics to foster creativity, critical thinking, and character development through diverse programs.",
    artsMusic: "Arts & Music",
    artsMusicDesc: "Visual arts, music, dance, and theater",
    sportsExcellence: "Sports Excellence",
    sportsExcellenceDesc: "Training with professional coaches",
    techEducation: "Tech Education",
    techEducationDesc: "Computer labs and coding classes",
    environmentalLearning: "Environmental Learning",
    environmentalLearningDesc: "Garden projects and sustainability",

    // Markets Page
    localMarkets: "Local Markets",
    marketsHero: "Shop Local, Support Community",
    marketsHeroDesc:
      "From fresh produce to traditional crafts, discover the vibrant marketplace of Kotulpur.",
    ourMarkets: "Our Markets",
    marketsDesc:
      "Vibrant marketplaces where local vendors showcase their best products.",
    centralMarket: "Kotulpur Central Market",
    centralMarketDesc:
      "The heart of local commerce with fresh produce and essentials.",
    morningVegSquare: "Morning Vegetable Square",
    morningVegSquareDesc:
      "Farm-fresh vegetables and fruits directly from local farmers.",
    textileEmporium: "Textile Emporium",
    textileEmporiumDesc:
      "Wide range of traditional and modern fabrics and garments.",
    wholesaleRetail: "Wholesale & Retail",
    freshProduce: "Fresh Produce",
    clothingFabric: "Clothing & Fabric",
    whatYouCanFind: "What You Can Find",
    freshVegetables: "Fresh Vegetables",
    fruits: "Fruits",
    bakedGoods: "Baked Goods",
    meatFish: "Meat & Fish",
    textiles: "Textiles",
    handicrafts: "Handicrafts",
    spices: "Spices",
    dairyProducts: "Dairy Products",
    freshFromFarm: "Fresh From Farm",
    farmToTable: "Farm to Table",
    farmToTableDesc:
      "Our markets connect local farmers directly with consumers, ensuring the freshest produce at fair prices. The Morning Vegetable Square opens daily before sunrise.",
    earlyBirdSpecial: "Early Bird Special",
    earlyBirdSpecialDesc: "5 AM - 8 AM",
    organicSection: "Organic Section",
    organicSectionDesc: "Certified organic",
    weeklyDiscounts: "Weekly Discounts",
    weeklyDiscountsDesc: "Every weekend",
    view: "View",

    // Transport Page
    transportServices: "Transport Services",
    transportHero: "Getting Around Made Easy",
    transportHeroDesc:
      "Well-connected transport network linking Kotulpur to the entire region.",
    transportRoutes: "Transport Routes",
    routesDesc: "Convenient and affordable connectivity to major destinations.",
    publicTransport: "Public Transport",
    cityCenter: "City Center",
    railwayStation: "Railway Station",
    busTerminal: "Bus Terminal",
    airport: "Airport",
    every15min: "Every 15 min",
    every30min: "Every 30 min",
    every20min: "Every 20 min",
    everyHour: "Every hour",
    schedule: "Schedule",
    transportOptions: "Transport Options",
    howYouCanTravel: "How You Can Travel",
    cityBuses: "City Buses",
    cityBusesDesc:
      "Regular bus service connecting all major areas within Kotulpur and beyond.",
    autoTaxi: "Auto & Taxi",
    autoTaxiDesc: "Ready availability of auto-rickshaws and metered taxis.",
    cycleStation: "Cycle Station",
    cycleStationDesc:
      "Eco-friendly cycle-sharing program for short-distance travel.",
    acNonAc: "AC & Non-AC",
    studentPasses: "Student passes",
    seniorDiscounts: "Senior discounts",
    availability247: "24/7 availability",
    gpsTracked: "GPS tracked",
    meteredFares: "Metered fares",
    firstHourFree: "First hour free",
    multipleStations: "Multiple stations",
    electricCycles: "Electric cycles",
    infrastructure: "Infrastructure",
    roadImprovements: "Road Improvements",
    roadDesc:
      "Kotulpur has seen significant infrastructure upgrades including widened roads, improved drainage, and modern bus stops with real-time tracking displays.",
    pavedRoads: "Paved Roads",
    busStops: "Bus Stops",
    parkingZones: "Parking Zones",
    cycleTracks: "Cycle Tracks",

    // Contact Page
    getInTouch: "Get in Touch",
    contactUs: "Contact Us",
    contactUsDesc: "Have questions or suggestions? We'd love to hear from you.",
    sendMessage: "Send Message",
    sendUsAMessage: "Send us a Message",
    yourName: "Your Name",
    enterYourName: "Enter your name",
    emailAddress: "Email Address",
    enterYourEmail: "Enter your email",
    message: "Message",
    howCanWeHelp: "How can we help you?",
    send: "Send Message",
    messageSent: "Message Sent!",
    contactInformation: "Contact Information",
    location: "Location",
    locationInfo: "Kotulpur, Main Road, Near Central Market",
    phone: "Phone",
    phoneInfo: "+91 98765 43210",
    email: "Email",
    emailInfo: "hello@kotulpur.in",
    hours: "Hours",
    hoursInfo: "Mon - Sat: 9:00 AM - 6:00 PM",
    followUs: "Follow Us",
    emergencyContacts: "Emergency Contacts",
    emergencyServices: "Emergency Services",
    police: "Police",
    fireBrigade: "Fire Brigade",

    // Footer
    vibrantLocality:
      "A vibrant locality built on community, tradition, and progress.",
    quickLinks: "Quick Links",
    resources: "Resources",
    news: "News",
    events: "Events",
    directory: "Directory",
    connect: "Connect",
    allRightsReserved: "All rights reserved.",

    // Scroll
    glimpseOf: "Glimpse of Kotulpur",
    glimpseDesc:
      "Explore the beauty and vibrancy of our locality through these captured moments",

    // Misc
    scroll: "Scroll",
  },
  bn: {
    home: "হোম",
    about: "সম্পর্কে",
    healthcare: "স্বাস্থ্যসেবা",
    education: "শিক্ষা",
    markets: "বাজার",
    transport: "পরিবহন",
    contact: "যোগাযোগ",
    contactUs: "যোগাযোগ করুন",
    services: "সেবা",
    welcomeToKotulpur: "কোটুলপুরের হৃদয়ে স্বাগতম",
    discover: "আবিষ্কার করুন",
    theBeautyOfKotulpur: "কোটুলপুরের সৌন্দর্য",
    tagline:
      "একটি জায়গা যেখানে ঐতিহ্য জীবন্ত হয়, সম্প্রদায় বিকাশ করে এবং প্রতিটি কোণ একটি গল্প বলে।",
    discoverKotulpur: "কোটুলপুর আবিষ্কার করুন",
    ourServices: "আমাদের সেবাসমূহ",
    featuredGallery: "বৈশিষ্ট্যযুক্ত গ্যালারি",
    popularInKotulpur: "কোটুলপুরে জনপ্রিয়",
    discoverLoved:
      "আমাদের সম্প্রদায় দ্বারা সংগৃহীত সবচেয়ে প্রিয় স্থান এবং মুহূর্তগুলি আবিষ্কার করুন",
    dragToExplore: "অন্বেষণ করতে টেনে আনুন",
    autoPlaying: "স্বয়ংক্রিয় গ্যালারি",
    ourServicesTitle: "আমাদের সেবাসমূহ",
    comprehensiveServices:
      "ব্যাপক সেবা যা কোটুলপুরকে একটি চমৎকার জায়গা করে তোলে।",
    healthcare: "স্বাস্থ্যসেবা",
    healthcareDesc: "সমস্ত বাসিন্দাদের জন্য মানসম্মত চিকিৎসা সেবা।",
    education: "শিক্ষা",
    educationDesc: "সকল বয়সের জন্য স্কুল এবং শিক্ষা কেন্দ্র।",
    markets: "বাজার",
    marketsDesc: "তাজা উৎপাদন এবং দৈনন্দিন প্রয়োজনীয় জিনিস।",
    transport: "পরিবহন",
    transportDesc: "প্রধান শহরের হাবের সাথে সংযুক্ত।",
    essentialInfrastructure: "অত্যাবশ্যক অবকাঠামো",
    coreServices: "মূল সেবাসমূহ",
    coreServicesDesc:
      "মূল সেবা যা আমাদের সম্প্রদায়কে মসৃণভাবে চালাতে সাহায্য করে।",
    learnMore: "আরও জানুন",
    communityCares: "একটি সম্প্রদায় যা যত্ন নেয়",
    communityCaresDesc:
      "কোটুলপুর শুধু একটি এলাকা নয়—এটি একটি পরিবার। উৎসবের সময় আমাদের সম্প্রদায় একসাথে আসে, প্রয়োজনের সময় একে অপরকে সহায়তা করে এবং সম্মিলিতভাবে আমাদের ভাগ করা স্থানগুলি বজায় রাখতে কাজ করে।",
    communityCaresDesc2:
      "পার্কে সকালের যোগব্যায়াম থেকে শিল্প ও সংস্কৃতির সন্ধ্যার অনুষ্ঠান পর্যন্ত, কোটুলপুরে জীবন প্রাণবন্ত এবং পরিপূর্ণ।",
    growingCommunity: "আমাদের বর্ধনশীল সম্প্রদায়ের অংশ হন",
    growingCommunityDesc:
      "আপনি দীর্ঘদিনের বাসিন্দা বা কোটুলপুরে নতুনই হোন না কেন, এখানে আপনার জন্য সবসময় একটি জায়গা আছে।",
    ourStory: "আমাদের গল্প",
    aboutKotulpur: "কোটুলপুর সম্পর্কে",
    aboutDesc:
      "কোটুলপুর একটি vibrant এলাকা যার একটি সমৃদ্ধ ইতিহাস এবং একটি প্রতিশ্রুতিশীল ভবিষ্যত আছে। অঞ্চলের হৃদয়ে অবস্থিত, আমাদের সম্প্রদায় তার উষ্ণ আতিথেয়তা, সাংস্কৃতিক ঐতিহ্য এবং একতারSpirit -এ পরিচিত।",
    exploreServices: "সেবা অন্বেষণ করুন",
    ourHeritage: "আমাদের ঐতিহ্য",
    legacyOfProgress: "অগ্রগতির একটি ঐতিহ্য",
    legacyDesc:
      "প্রতিষ্ঠিত হয়েছে প্রজন্ম আগে, কোটুলপুর একটি ছোট গ্রাম থেকে একটি সমৃদ্ধ সম্প্রদায়ে বিকশিত হয়েছে যা ঐতিহ্য এবং আধুনিক অগ্রগতির ভারসাম্য বজায় রাখে।",
    legacyDesc2:
      "আমাদের পূর্বপুরুষরা আজ আমরা যা উপভোগ করি তার ভিত্তি স্থাপন করেছিলেন—একটি জায়গা যেখানে প্রতিবেশীরা একে অপরকে নামে চেনেন, উৎসব পূর্ণ উৎসাহের সাথে উদযাপিত হয় এবং প্রতিটি নতুন সদস্যকে উন্মুক্ত বাহু দিয়ে স্বাগত জানানো হয়।",
    whatWeStandFor: "আমরা কি জন্য দাঁড়িয়েছি",
    ourValues: "আমাদের মূল্যবোধ",
    valuesDesc: "নীতি যা আমাদের সম্প্রদায়কে এগিয়ে নিয়ে যায়।",
    unity: "ঐক্য",
    unityDesc: "একসাথে আমরা শক্তিশালী",
    educationValue: "শিক্ষা",
    educationValueDesc: "জীবনের জন্য শেখা",
    culture: "সংস্কৃতি",
    cultureDesc: "আমাদের ঐতিহ্য সংরক্ষণ",
    growth: "বৃদ্ধি",
    growthDesc: "সামঞ্জস্যে অগ্রগতি",
    residents: "বাসিন্দা",
    businesses: "ব্যবসা",
    yearsOfHistory: "ইতিহাসের বছর",
    wantToLearnMore: "আরও জানতে চান?",
    wantToLearnMoreDesc:
      "আমাদের সেবাগুলি অন্বেষণ করুন এবং কোটুলপুরের সবকিছু আবিষ্কার করুন।",
    servicesWeProvide: "আমরা যে সেবাগুলি প্রদান করি",
    servicesDesc:
      "অত্যাবশ্যক ইউটিলিটি থেকে শুরু করে সম্প্রদায় প্রোগ্রাম পর্যন্ত, আমরা কোটুলপুরের সমস্ত বাসিন্দাদের জন্য একটি উচ্চ মানের জীবন নিশ্চিত করি।",
    waterSupply: "জল সরবরাহ",
    waterSupplyDesc: "সমস্ত এলাকায় 24/7 পরিষ্কার জল বিতরণ।",
    electricity: "বিদ্যুৎ",
    electricityDesc: "ন্যূনতম বিভ্রাট সহ নির্ভরযোগ্য বিদ্যুৎ গ্রিড।",
    communityPrograms: "সম্প্রদায় প্রোগ্রাম",
    togetherWeGrow: "একসাথে আমরা বাড়ি",
    greenInitiative: "সবুজ কোটুলপুর উদ্যোগ",
    greenInitiativeDesc:
      "বৃক্ষরোপণ, বর্জ্য ব্যবস্থাপনা এবং পরিবেশ সচেতনতা কর্মসূচি।",
    seniorCitizenCare: "প্রবীন নাগরিক সেবা",
    seniorCitizenCareDesc:
      "স্বাস্থ্য পরীক্ষা, সামাজিক অনুষ্ঠান এবং বয়স্কদের জন্য কল্যাণ প্রকল্প।",
    youthDevelopment: "তরুণ উন্নয়ন",
    youthDevelopmentDesc:
      "ক্রীড়া টুর্নামেন্ট, দক্ষতা কর্মশালা এবং কর্ম সহায়তা কর্মসূচি।",
    culturalPreservation: "সাংস্কৃতিক সংরক্ষণ",
    culturalPreservationDesc:
      "সঙ্গীত, নৃত্য, শিল্প প্রদর্শনী এবং আমাদের ঐতিহ্য উদযাপনকারী উৎসব।",
    getInvolved: "জড়িত হন",
    needAssistance: "সাহায্য প্রয়োজন?",
    needAssistanceDesc:
      "আমাদের সহায়তা দল যেকোনো প্রশ্ন বা উদ্বেগে আপনাকে সাহায্য করতে এখানে।",
    contactSupport: "সহায়তা যোগাযোগ করুন",
    healthcareServices: "স্বাস্থ্যসেবা",
    healthcareHero: "প্রতিটি বাসিন্দার জন্য মানসম্মত স্বাস্থ্যসেবা",
    healthcareHeroDesc:
      "আমাদের সম্প্রদায়কে স্বাস্থ্যকর রাখতে ব্যাপক চিকিৎসা সুবিধা এবং কল্যাণ প্রোগ্রাম।",
    medicalFacilities: "চিকিৎসা সুবিধা",
    medicalFacilitiesDesc:
      "কোটুলপুর এবং আশেপাশের এলাকায় সেবা প্রদানকারী আধুনিক স্বাস্থ্যসেবা অবকাঠামো।",
    communityHealthCenter: "কোটুলপুর কমিউনিটি হেলথ সেন্টার",
    communityHealthCenterDesc: "24/7 জরুরি সেবা এবং সাধারণ পরামর্শ।",
    lifecareDiagnostics: "লাইফকেয়ার ডায়াগনস্টিকস",
    lifecareDiagnosticsDesc: "উন্নত প্যাথলজি এবং ইমেজিং সেবা।",
    dentalCarePlus: "ডেন্টাল কেয়ার প্লাস",
    dentalCarePlusDesc: "আধুনিক সরঞ্জাম সহ সম্পূর্ণ দাঁতের যত্ন।",
    primaryCare: "প্রাথমিক চিকিৎসা",
    diagnosticLab: "ডায়াগনস্টিক ল্যাব",
    dentalClinic: "ডেন্টাল ক্লিনিক",
    servicesWeOffer: "আমরা যে সেবা প্রদান করি",
    emergencyCare: "জরুরি চিকিৎসা",
    emergencyCareDesc: "24/7 অ্যাম্বুলেন্স",
    generalMedicine: "সাধারণ ওষুধ",
    generalMedicineDesc: "অভিজ্ঞ চিকিৎসক",
    diagnostics: "ডায়াগনস্টিক্স",
    diagnosticsDesc: "ল্যাব টেস্ট, এক্স-রে, এমআরআই",
    pharmacy: "ফার্মেসি",
    pharmacyDesc: "সারাদিন",
    inpatientCare: "ভর্তি রোগী যত্ন",
    inpatientCareDesc: "24/7 নার্সিং",
    dentalServices: "দাঁতের সেবা",
    dentalServicesDesc: "সব চিকিৎসা",
    eyeCare: "চোখের যত্ন",
    eyeCareDesc: "চক্ষু বিশেষজ্ঞ",
    wellness: "সুস্থতা",
    wellnessDesc: "योগ, ধ্যান",
    patientsYearly: "বার্ষিক রোগী",
    qualifiedDoctors: "যোগ্য ডাক্তার",
    emergency: "জরুরি",
    satisfaction: "সন্তুষ্টি",
    details: "বিস্তারিত",
    beds: "50+",
    tests: "200+",
    doctors: "5",
    educationServices: "শিক্ষা সেবা",
    educationHero: "জ্ঞানের মাধ্যমে ক্ষমতায়ন",
    educationHeroDesc:
      "প্রি-স্কুল থেকে উচ্চশিক্ষা পর্যন্ত, কোটুলপুর আগামীর জন্য উজ্জ্বল মনকে পুষ্ট করে।",
    educationalInstitutions: "শিক্ষা প্রতিষ্ঠান",
    institutionsDesc:
      "নিবেদিত শিক্ষক এবং আধুনিক শিক্ষাবিদ্যা দ্বারা প্রতিটি স্তরে মানসম্মত শিক্ষা।",
    kotulpurCentralSchool: "কোটুলপুর সেন্ট্রাল স্কুল",
    kotulpurCentralSchoolDesc:
      "আধুনিক অবকাঠামো এবং অভিজ্ঞ শিক্ষক সহ সিবিএসই সংযুক্ত স্কুল।",
    govindaramCollege: "গোবিন্দরাম কলেজ",
    govindaramCollegeDesc:
      "আর্টস, সায়েন্স এবং কমার্স স্ট্রিম সহ চমৎকার প্লেসমেন্ট রেকর্ড।",
    tinyTotsPreSchool: "টিনি টটস প্রি-স্কুল",
    tinyTotsPreSchoolDesc:
      "সামগ্রিক বিকাশের উপর দৃষ্টি নিবদ্ধ প্রারম্ভিক শৈশব শিক্ষা।",
    k12: "কে-12",
    higherEducation: "উচ্চশিক্ষা",
    prePrimary: "প্রি-প্রাথমিক",
    students: "শিক্ষার্থী",
    teachers: "শিক্ষক",
    passRate: "পাস রেট",
    awards: "পুরস্কার",
    beyondTextbooks: "পাঠ্যপুস্তকের বাইরে",
    holisticDevelopment: "সামগ্রিক উন্নয়ন",
    holisticDesc:
      "আমাদের প্রতিষ্ঠানগুলি বৈচিত্র্যময় প্রোগ্রামের মাধ্যমে সৃজনশীলতা, সমালোচনামূলক চিন্তা এবং চরিত্র বিকাশ বিকাশে সহায়তা করে।",
    artsMusic: "আর্টস ও মিউজিক",
    artsMusicDesc: "ভিজ্যুয়াল আর্টস, মিউজিক, ডান্স এবং থিয়েটার প্রোগ্রাম",
    sportsExcellence: "ক্রীড়া শ্রেষ্ঠত্ব",
    sportsExcellenceDesc: "পেশাদার কোচদের সাথে প্রশিক্ষণ",
    techEducation: "প্রযুক্তি শিক্ষা",
    techEducationDesc: "কম্পিউটার ল্যাব এবং কোডিং ক্লাস",
    environmentalLearning: "পরিবেশগত শিক্ষা",
    environmentalLearningDesc: "গার্ডেন প্রকল্প এবং টেকসইতা",
    localMarkets: "স্থানীয় বাজার",
    marketsHero: "স্থানীয় কিনুন, সম্প্রদায়কে সমর্থন করুন",
    marketsHeroDesc:
      "তাজা উৎপাদন থেকে শুরু করে ঐতিহ্যবাহী শিল্পকলা পর্যন্ত, কোটুলপুরের vibrant বাজার আবিষ্কার করুন।",
    ourMarkets: "আমাদের বাজার",
    marketsDesc:
      "Vibrant marketplaces যেখানে স্থানীয় বিক্রেতারা তাদের সেরা পণ্য প্রদর্শন করে।",
    centralMarket: "কোটুলপুর সেন্ট্রাল মার্কেট",
    centralMarketDesc:
      "তাজা উৎপাদন এবং প্রয়োজনীয় জিনিস সহ স্থানীয় বাণিজ্যের হৃদয়।",
    morningVegSquare: "সকালের সবজি স্কোয়ার",
    morningVegSquareDesc: "স্থানীয় কৃষকদের কাছ থেকে সরাসরি তাজা সবজি এবং ফল।",
    textileEmporium: "টেক্সটাইল এম্পোরিয়াম",
    textileEmporiumDesc:
      "ঐতিহ্যবাহী এবং আধুনিক কাপড় এবং garments এর বিস্তৃত পরিসর।",
    wholesaleRetail: "পাইকারি ও খুচরা",
    freshProduce: "তাজা উৎপাদন",
    clothingFabric: "কাপড় ও গার্মেন্টস",
    whatYouCanFind: "আপনি কি খুঁজে পেতে পারেন",
    freshVegetables: "তাজা সবজি",
    fruits: "ফল",
    bakedGoods: "বেকড গুডস",
    meatFish: "মাংস ও মাছ",
    textiles: "টেক্সটাইল",
    handicrafts: "হস্তশিল্প",
    spices: "মশলা",
    dairyProducts: "দুগ্ধজাত পণ্য",
    freshFromFarm: "খামার থেকে তাজা",
    farmToTable: "খামার থেকে টেবিল",
    farmToTableDesc:
      "আমাদের বাজার সরাসরি ভোক্তাদের সাথে স্থানীয় কৃষকদের সংযুক্ত করে, ন্যায্য মূল্যে সবচেয়ে তাজা উৎপাদন নিশ্চিত করে।",
    earlyBirdSpecial: "ভোরের বিশেষ",
    earlyBirdSpecialDesc: "সকাল ৫টা - ৮টা",
    organicSection: "জৈব বিভাগ",
    organicSectionDesc: "প্রত্যয়িত জৈব",
    weeklyDiscounts: "সাপ্তাহিক ছাড়",
    weeklyDiscountsDesc: "প্রতি সপ্তাহান্তে",
    view: "দেখুন",
    transportServices: "পরিবহন সেবা",
    transportHero: "চারপাশে ঘোরা সহজ",
    transportHeroDesc:
      "কোটুলপুরকে সমগ্র অঞ্চলের সাথে সংযুক্ত করে ভাল-সংযুক্ত পরিবহন নেটওয়ার্ক।",
    transportRoutes: "পরিবহন রুট",
    routesDesc: "প্রধান গন্তব্যগুলিতে সুবিধাজনক এবং সাশ্রয়ী সংযোগ।",
    publicTransport: "পাবলিক পরিবহন",
    cityCenter: "শহরের কেন্দ্র",
    railwayStation: "রেলওয়ে স্টেশন",
    busTerminal: "বাস টার্মিনাল",
    airport: "বিমানবন্দর",
    every15min: "প্রতি ১৫ মিনিট",
    every30min: "প্রতি ৩০ মিনিট",
    every20min: "প্রতি ২০ মিনিট",
    everyHour: "প্রতি ঘণ্টায়",
    schedule: "সময়সূচী",
    transportOptions: "পরিবহন বিকল্প",
    howYouCanTravel: "আপনি কীভাবে ভ্রমণ করতে পারেন",
    cityBuses: "সিটি বাস",
    cityBusesDesc:
      "কোটুলপুরের মধ্যে এবং তার বাইরে সমস্ত প্রধান এলাকাকে সংযুক্ত করে নিয়মিত বাস সেবা।",
    autoTaxi: "অটো ও ট্যাক্সি",
    autoTaxiDesc:
      "পয়েন্ট-টু-পয়েন্ট ভ্রমণের জন্য auto-rickshaws এবং মিটারযুক্ত ট্যাক্সি প্রস্তুত উপলব্ধতা।",
    cycleStation: "সাইকেল স্টেশন",
    cycleStationDesc:
      "স্থানীয় এলাকার মধ্যে স্বল্প দূরত্বে ভ্রমণের জন্য পরিবেশবান্ধব সাইকেল-শেয়ারিং প্রোগ্রাম।",
    acNonAc: "এসি ও নন-এসি",
    studentPasses: "ছাত্র পাস",
    seniorDiscounts: "প্রবীন ছাড়",
    availability247: "২৪/৭ প্রাপ্যতা",
    gpsTracked: "জিপিএস ট্র্যাকড",
    meteredFares: "মিটারভাড়া",
    firstHourFree: "প্রথম ঘণ্টা বিনামূল্যে",
    multipleStations: "একাধিক স্টেশন",
    electricCycles: "ইলেকট্রিক সাইকেল",
    infrastructure: "অবকাঠামো",
    roadImprovements: "রাস্তার উন্নতি",
    roadDesc:
      "কোটুলপুরে উল্লেখযোগ্য অবকাঠামো উন্নয়ন হয়েছে যার মধ্যে প্রশস্ত রাস্তা, উন্নত নর্দমা এবং রিয়েল-টাইম ট্র্যাকিং ডিসপ্লে সহ আধুনিক বাস স্টপ অন্তর্ভুক্ত।",
    pavedRoads: "ফ্ল্যাগ রোড",
    busStops: "বাস স্টপ",
    parkingZones: "পার্কিং জোন",
    cycleTracks: "সাইকেল ট্র্যাক",
    getInTouch: "যোগাযোগ করুন",
    contactUsDesc: "প্রশ্ন বা পরামর্শ আছে? আমরা আপনার কাছ থেকে শুনতে চাই।",
    sendMessage: "বার্তা পাঠান",
    sendUsAMessage: "আমাদের একটি বার্তা পাঠান",
    yourName: "আপনার নাম",
    enterYourName: "আপনার নাম দিন",
    emailAddress: "ইমেইল ঠিকানা",
    enterYourEmail: "আপনার ইমেইল দিন",
    message: "বার্তা",
    howCanWeHelp: "আমরা কীভাবে আপনাকে সাহায্য করতে পারি?",
    send: "বার্তা পাঠান",
    messageSent: "বার্তা পাঠানো হয়েছে!",
    contactInformation: "যোগাযোগ তথ্য",
    location: "অবস্থান",
    locationInfo: "কোটুলপুর, মূল রোড, সেন্ট্রাল মার্কেটের কাছে",
    phone: "ফোন",
    phoneInfo: "+91 98765 43210",
    email: "ইমেইল",
    emailInfo: "hello@kotulpur.in",
    hours: "ঘণ্টা",
    hoursInfo: "সোম - শনি: সকাল ৯টা - সন্ধ্যা ৬টা",
    followUs: "আমাদের অনুসরণ করুন",
    emergencyContacts: "জরুরি যোগাযোগ",
    emergencyServices: "জরুরি সেবা",
    police: "পুলিশ",
    fireBrigade: "ফায়ার ব্রিগেড",
    vibrantLocality:
      "সম্প্রদায়, ঐতিহ্য এবং অগ্রগতির উপর নির্মিত একটি vibrant এলাকা।",
    quickLinks: "দ্রুত লিঙ্ক",
    resources: "রিসোর্স",
    news: "খবর",
    events: "ঘটনা",
    directory: "ডিরেক্টরি",
    connect: "সংযুক্ত",
    allRightsReserved: "সর্বস্বত্ব সংরক্ষিত।",
    glimpseOf: "কোটুলপুরের ঝলক",
    glimpseDesc: "আমাদের এলাকার সৌন্দর্য এবং প্রাণবন্ততা অন্বেষণ করুন",
    scroll: "স্ক্রল",
  },
  hi: {
    home: "होम",
    about: "हमारे बारे में",
    healthcare: "स्वास्थ्य सेवा",
    education: "शिक्षा",
    markets: "बाज़ार",
    transport: "परिवहन",
    contact: "संपर्क",
    contactUs: "संपर्क करें",
    services: "सेवाएं",
    welcomeToKotulpur: "कोटुलपुर के दिल में स्वागत है",
    discover: "खोजें",
    theBeautyOfKotulpur: "कोटुलपुर की सुंदरता",
    tagline:
      "एक ऐसी जगह जहां परंपराएं जीवित हैं, समुदाय पनपते हैं, और हर कोना एक कहानी कहता है।",
    discoverKotulpur: "कोटुलपुर खोजें",
    ourServices: "हमारी सेवाएं",
    featuredGallery: "फीचर्ड गैलरी",
    popularInKotulpur: "कोटुलपुर में लोकप्रिय",
    discoverLoved:
      "हमारे समुदाय द्वारा दिए गए सबसे पसंद किए जाने वाले स्थानों और पलों को खोजें",
    dragToExplore: "खोजने के लिए खींचें",
    autoPlaying: "ऑटो-प्लेइंग गैलरी",
    ourServicesTitle: "हमारी सेवाएं",
    comprehensiveServices:
      "व्यापक सेवाएं जो कोटुलपुर को एक अद्भुत जगह बनाती हैं।",
    learnMore: "और जानें",
    communityCares: "एक समुदाय जो देखभाल करता है",
    communityCaresDesc:
      "कोटुलपुर सिर्फ एक इलाका नहीं है—यह एक परिवार है। हमारा समुदाय त्योहारों के समय एक साथ आता है, जरूरत के समय एक दूसरे का समर्थन करता है, और साझा जगहों को बनाए रखने के लिए सामूहिक रूप से काम करता है।",
    communityCaresDesc2:
      "पार्क में सुबह योग सत्र से लेकर शाम के सांस्कृतिक कार्यक्रमों तक, कोटुलपुर में जीवन जीवंत और पूर्ण है।",
    growingCommunity: "हमारे बढ़ते समुदाय का हिस्सा बनें",
    growingCommunityDesc:
      "चाहे आप कोटुलपुर के लंबे समय से निवासी हों या नए हों, यहां आपके लिए हमेशा जगह है।",
    ourStory: "हमारी कहानी",
    aboutKotulpur: "कोटुलपुर के बारे में",
    aboutDesc:
      "कोटुलपुर एक vibrant इलाका है जिसका एक समृद्ध इतिहास और एक उज्ज्वल भविष्य है। क्षेत्र के हृदय में स्थित, हमारा समुदाय अपनी गर्म आतिथ्य, सांस्कृतिक विरासत और एकता की भावना के लिए जाना जाता है।",
    exploreServices: "सेवाएं खोजें",
    ourHeritage: "हमारी विरासत",
    legacyOfProgress: "प्रगति की विरासत",
    legacyDesc:
      "पीढ़ियों पहले स्थापित, कोटुलपुर एक छोटे गाँव से एक समृद्ध समुदाय में बढ़ गया है जो परंपरा और आधुनिक प्रगति के बीच संतुलन बनाए रखता है।",
    legacyDesc2:
      "हमारे पूर्वजों ने आज जो हम आनंद लेते हैं उसकी नींव रखी—एक ऐसी जगह जहां पड़ोसी एक दूसरे को नाम से जानते हैं, त्योहार पूरे उत्साह के साथ मनाए जाते हैं, और हर नए सदस्य को खुली बाहों से स्वागत किया जाता है।",
    whatWeStandFor: "हम किसके लिए खड़े हैं",
    ourValues: "हमारे मूल्य",
    valuesDesc: "सिद्धांत जो हमारे समुदाय को आगे बढ़ाते हैं।",
    unity: "एकता",
    unityDesc: "एक साथ हम मजबूत खड़े हैं",
    educationValue: "शिक्षा",
    educationValueDesc: "जीवन के लिए सीखना",
    culture: "संस्कृति",
    cultureDesc: "हमारी विरासत का संरक्षण",
    growth: "विकास",
    growthDesc: "सामंजस्य में प्रगति",
    residents: "निवासी",
    businesses: "व्यापार",
    yearsOfHistory: "इतिहास के वर्ष",
    wantToLearnMore: "और जानना चाहते हैं?",
    wantToLearnMoreDesc:
      "हमारी सेवाओं का पता लगाएं और कोटुलपुर की सब कुछ खोजें।",
    servicesWeProvide: "हम जो सेवाएं प्रदान करते हैं",
    servicesDesc:
      "आवश्यक उपयोगिताओं से लेकर सामुदायिक कार्यक्रमों तक, हम कोटुलपुर के सभी निवासियों के लिए उच्च गुणवत्ता वाला जीवन सुनिश्चित करते हैं।",
    learnMore: "और जानें",
    communityPrograms: "सामुदायिक कार्यक्रम",
    togetherWeGrow: "एक साथ हम बढ़ते हैं",
    getInvolved: "शामिल हों",
    needAssistance: "सहायता चाहिए?",
    needAssistanceDesc:
      "हमारी सहायता टीम किसी भी प्रश्न या चिंता में आपकी मदद के लिए यहां है।",
    contactSupport: "समर्थन से संपर्क करें",
    healthcare: "स्वास्थ्य सेवा",
    healthcareDesc: "सभी निवासियों के लिए गुणवत्तापूर्ण चिकित्सा देखभाल।",
    education: "शिक्षा",
    educationDesc: "सभी उम्र के लिए स्कूल और सीखने के केंद्र।",
    markets: "बाज़ार",
    marketsDesc: "ताजा उत्पाद और दैनिक आवश्यकताएं।",
    transport: "परिवहन",
    transportDesc: "प्रमुख शहरी केंद्रों से जुड़ा।",
    healthcareServices: "स्वास्थ्य सेवाएं",
    healthcareHero: "हर निवासी के लिए गुणवत्तापूर्ण स्वास्थ्य सेवा",
    healthcareHeroDesc:
      "हमारे समुदाय को स्वस्थ रखने के लिए व्यापक चिकित्सा सुविधाएं और कल्याण कार्यक्रम।",
    medicalFacilities: "चिकित्सा सुविधाएं",
    medicalFacilitiesDesc:
      "कोटुलपुर और आसपास के क्षेत्रों की सेवा करने वाली अत्याधुनिक स्वास्थ्य अवसंरचना।",
    learnMore: "और जानें",
    servicesWeOffer: "हम जो सेवा प्रदान करते हैं",
    emergencyCare: "आपातकालीन देखभाल",
    generalMedicine: "सामान्य चिकित्सा",
    diagnostics: "निदान",
    pharmacy: "फार्मेसी",
    inpatientCare: "अंतःरोगी देखभाल",
    dentalServices: "दंत सेवाएं",
    eyeCare: "आंखों की देखभाल",
    wellness: "कल्याण",
    patientsYearly: "सालाना रोगी",
    qualifiedDoctors: "योग्य डॉक्टर",
    emergency: "आपातकालीन",
    satisfaction: "संतुष्टि",
    details: "विवरण",
    educationServices: "शिक्षा सेवाएं",
    educationHero: "ज्ञान के माध्यम से सशक्तिकरण",
    educationHeroDesc:
      "प्री-स्कूल से उच्च शिक्षा तक, कोटुलपुर कल के उज्ज्वल मनों को पोषित करता है।",
    educationalInstitutions: "शैक्षणिक संस्थान",
    institutionsDesc:
      "समर्पित शिक्षकों और आधुनिक शिक्षाशास्त्र द्वारा हर स्तर पर गुणवत्तापूर्ण शिक्षा।",
    students: "छात्र",
    teachers: "शिक्षक",
    passRate: "पास दर",
    awards: "पुरस्कार",
    holisticDevelopment: "समग्र विकास",
    localMarkets: "स्थानीय बाज़ार",
    marketsHero: "स्थानीय खरीदें, समुदाय का समर्थन करें",
    marketsHeroDesc:
      "ताजा उत्पाद से लेकर पारंपरिक शिल्प तक, कोटुलपुर के vibrant बाज़ार की खोज करें।",
    ourMarkets: "हमारे बाज़ार",
    marketsDesc:
      "जीवंत बाज़ार जहां स्थानीय विक्रेता अपने सर्वश्रेष्ठ उत्पाद प्रदर्शित करते हैं।",
    whatYouCanFind: "आप क्या पा सकते हैं",
    freshVegetables: "ताजी सब्जियां",
    fruits: "फल",
    bakedGoods: "बेक्ड गूड्स",
    meatFish: "मांस और मछली",
    textiles: "कपड़ा",
    handicrafts: "हस्तशिल्प",
    spices: "मसाले",
    dairyProducts: "डेयरी उत्पाद",
    freshFromFarm: "खेत से ताजा",
    farmToTable: "खेत से थाली",
    view: "देखें",
    transportServices: "परिवहन सेवाएं",
    transportHero: "आसानी से घूमना",
    transportHeroDesc:
      "कोटुलपुर को पूरे क्षेत्र से जोड़ने वाला अच्छी तरह से जुड़ा परिवहन नेटवर्क।",
    transportRoutes: "परिवहन मार्ग",
    routesDesc: "प्रमुख गंतव्यों के लिए सुविधाजनक और किफायती कनेक्टिविटी।",
    publicTransport: "सार्वजनिक परिवहन",
    cityCenter: "शहर का केंद्र",
    railwayStation: "रेलवे स्टेशन",
    busTerminal: "बस टर्मिनल",
    airport: "हवाई अड्डा",
    schedule: "समय-सारणी",
    transportOptions: "परिवहन विकल्प",
    howYouCanTravel: "आप कैसे यात्रा कर सकते हैं",
    cityBuses: "सिटी बसें",
    autoTaxi: "ऑटो और टैक्सी",
    cycleStation: "साइकिल स्टेशन",
    infrastructure: "अवसंरचना",
    roadImprovements: "सड़क सुधार",
    pavedRoads: "कठपुतली सड़कें",
    busStops: "बस स्टॉप",
    parkingZones: "पार्किंग ज़ोन",
    cycleTracks: "साइकिल ट्रैक",
    getInTouch: "संपर्क करें",
    contactUsDesc: "प्रश्न या सुझाव हैं? हम आपसे सुनना पसंद करेंगे।",
    sendMessage: "संदेश भेजें",
    sendUsAMessage: "हमें एक संदेश भेजें",
    yourName: "आपका नाम",
    enterYourName: "अपना नाम दर्ज करें",
    emailAddress: "ईमेल पता",
    enterYourEmail: "अपना ईमेल दर्ज करें",
    message: "संदेश",
    howCanWeHelp: "हम आपकी कैसे मदद कर सकते हैं?",
    send: "संदेश भेजें",
    messageSent: "संदेश भेजा गया!",
    contactInformation: "संपर्क जानकारी",
    location: "स्थान",
    locationInfo: "कोटुलपुर, मेन रोड, सेंट्रल मार्केट के पास",
    phone: "फोन",
    phoneInfo: "+91 98765 43210",
    email: "ईमेल",
    emailInfo: "hello@kotulpur.in",
    hours: "घंटे",
    hoursInfo: "सोम - शनि: सुबह 9:00 - शाम 6:00",
    followUs: "हमें फॉलो करें",
    emergencyContacts: "आपातकालीन संपर्क",
    emergencyServices: "आपातकालीन सेवाएं",
    police: "पुलिस",
    fireBrigade: "फायर ब्रिगेड",
    vibrantLocality: "समुदाय, परंपरा और प्रगति पर निर्मित एक vibrant इलाका।",
    quickLinks: "त्वरित लिंक",
    resources: "संसाधन",
    news: "समाचार",
    events: "कार्यक्रम",
    directory: "निर्देशिका",
    connect: "जुड़ें",
    allRightsReserved: "सर्वाधिकार सुरक्षित।",
    glimpseOf: "कोटुलपुर की झलक",
    glimpseDesc: "हमारे इलाके की सुंदरता और जीवंतता का पता लगाएं",
    scroll: "स्क्रॉल",
  },
};

const languages = [
  { code: "en", label: "English", native: "EN" },
  { code: "bn", label: "Bengali", native: "বাং" },
  { code: "hi", label: "Hindi", native: "हिं" },
];

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    const saved = localStorage.getItem("kotulpur-lang");
    return languages.find((l) => l.code === saved) || languages[0];
  });

  useEffect(() => {
    localStorage.setItem("kotulpur-lang", currentLang.code);
  }, [currentLang]);

  const t = (key) =>
    translations[currentLang.code]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider
      value={{ currentLang, setCurrentLang, t, languages }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export { languages };
